import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

/**
 * English / Hindi. The English text is the key: t("Fleet optimizer") returns the Hindi translation when Hindi is on
 * and the English text otherwise, so anything not yet translated simply stays in English. Hindi covers navigation,
 * page openers, headline figures, the main controls and the guided tour; detailed tables, chart labels and the
 * plan explanations generated by the model stay in English. Placeholders: t("{n} ships", { n: 29 }).
 */
export type Lang = "en" | "hi";

const HI: Record<string, string> = {
  // navigation and shell
  "Overview": "अवलोकन",
  "Fleet optimizer": "बेड़ा अनुकूलक",
  "Compare plans": "योजनाओं की तुलना",
  "Fuel prediction": "ईंधन पूर्वानुमान",
  "Fuel & policy lab": "ईंधन और नीति प्रयोगशाला",
  "Compliance": "अनुपालन",
  "Benchmarks": "बेंचमार्क",
  "Methodology": "कार्यप्रणाली",
  "Guided tour (2 min)": "गाइडेड टूर (2 मिनट)",
  "green fleet decisions": "हरित बेड़ा निर्णय",
  "auto": "स्वतः",
  "light": "हल्का",
  "dark": "गहरा",
  "Loading…": "लोड हो रहा है…",
  "India coastal & near-sea network": "भारत तटीय और निकट-समुद्री नेटवर्क",
  "EU trade network": "EU व्यापार नेटवर्क",

  // overview
  "Scenario overview · {year}": "परिदृश्य अवलोकन · {year}",
  "Quantum-inspired decision support for green fleet deployment: predict fuel use, then choose vessel mix, capacity, speed, fuel and shore power per service to cut fuel, lifecycle emissions and cost.":
    "हरित बेड़ा परिनियोजन के लिए क्वांटम-प्रेरित निर्णय सहायता: ईंधन खपत का पूर्वानुमान लगाएँ, फिर हर सेवा के लिए जहाज़ों का मिश्रण, क्षमता, गति, ईंधन और तट-बिजली चुनें, ताकि ईंधन, जीवनचक्र उत्सर्जन और लागत घटे।",
  "Take the 2-minute tour": "2 मिनट का टूर देखें",
  "Optimize this fleet": "इस बेड़े का अनुकूलन करें",
  "Back to optimizer": "अनुकूलक पर लौटें",
  "Current practice · well-to-wake emissions": "मौजूदा तरीका · वेल-टू-वेक उत्सर्जन",
  "Mt CO₂e / yr": "Mt CO₂e / वर्ष",
  "{cost} a year · {ships} ships. Run the optimizer to find better plans.":
    "{cost} प्रति वर्ष · {ships} जहाज़। बेहतर योजनाएँ खोजने के लिए अनुकूलक चलाएँ।",
  "{label} · emissions vs today": "{label} · आज की तुलना में उत्सर्जन",
  "well-to-wake GHG": "वेल-टू-वेक GHG",
  "all constraints met": "सभी शर्तें पूरी",
  "constraints violated": "शर्तों का उल्लंघन",
  "fuel": "ईंधन",
  "cost": "लागत",
  "ships": "जहाज़",
  "Services": "सेवाएँ",
  "{nm} nm of sea routes": "{nm} nm समुद्री मार्ग",
  "FuelEU target": "FuelEU लक्ष्य",
  "gCO₂e / MJ (well-to-wake)": "gCO₂e / MJ (वेल-टू-वेक)",
  "CII reduction": "CII कटौती",
  "below the 2019 reference line": "2019 संदर्भ रेखा से नीचे",
  "EU ETS price": "EU ETS मूल्य",
  "per t CO₂e": "प्रति t CO₂e",
  "per tonne": "प्रति टन",
  "e-Ammonia": "ई-अमोनिया",
  "Network": "नेटवर्क",
  "fuels bunkerable within range in {year}": "{year} में दायरे के भीतर उपलब्ध ईंधन",
  "Current practice": "मौजूदा तरीका",

  // page openers
  "Deliverables 2–3 · Optimization": "डिलिवरेबल 2–3 · अनुकूलन",
  "Choose vessel mix, capacity, speed, fuel and shore power for every service, minimising fuel, well-to-wake emissions and cost under demand, schedule, fleet, CII and FuelEU constraints.":
    "हर सेवा के लिए जहाज़ों का मिश्रण, क्षमता, गति, ईंधन और तट-बिजली चुनें: माँग, समय-सारिणी, बेड़े, CII और FuelEU की शर्तों के भीतर ईंधन, वेल-टू-वेक उत्सर्जन और लागत न्यूनतम करें।",
  "Plans · scenarios · trade-offs": "योजनाएँ · परिदृश्य · ट्रेड-ऑफ़",
  "Save any plan from the optimizer, then put two side by side: the same network under different scenarios (a Red Sea closure, a higher carbon price) or two points on one trade-off curve.":
    "अनुकूलक से कोई भी योजना सहेजें, फिर दो को साथ-साथ रखें: अलग-अलग परिदृश्यों में एक ही नेटवर्क (लाल सागर बंद होना, ऊँचा कार्बन मूल्य) या एक ही ट्रेड-ऑफ़ वक्र के दो बिंदु।",
  "Deliverable 1 · Prediction": "डिलिवरेबल 1 · पूर्वानुमान",
  "Fuel consumption prediction": "ईंधन खपत पूर्वानुमान",
  "Q-PHYS combines ship physics with a QPSO-tuned monotone booster and a Matrix-Product-State tensor network (a quantum-inspired model). Inputs follow the PS: speed, load, weather and vessel type.":
    "Q-PHYS जहाज़ की भौतिकी को QPSO से ट्यून किए गए मोनोटोन बूस्टर और मैट्रिक्स-प्रोडक्ट-स्टेट टेंसर नेटवर्क (एक क्वांटम-प्रेरित मॉडल) से जोड़ता है। इनपुट समस्या कथन के अनुसार हैं: गति, भार, मौसम और जहाज़ का प्रकार।",
  "Scenario simulation · 2025–2050": "परिदृश्य सिमुलेशन · 2025–2050",
  "Scenario analysis for alternative fuels: how the optimal fleet shifts from 2025 to 2050, what each measure costs per tonne abated, how robust a plan is, and how close quantum-inspired annealing gets to the exact optimum.":
    "वैकल्पिक ईंधनों का परिदृश्य विश्लेषण: 2025 से 2050 तक इष्टतम बेड़ा कैसे बदलता है, हर उपाय से प्रति टन कटौती की लागत क्या है, कोई योजना कितनी मज़बूत है, और क्वांटम-प्रेरित एनीलिंग सटीक इष्टतम के कितने क़रीब पहुँचती है।",
  "Regulatory compliance": "नियामक अनुपालन",
  "{label} in {year}: IMO Carbon Intensity Indicator per ship, FuelEU Maritime pooled GHG intensity and EU ETS exposure.":
    "{year} में {label}: प्रति जहाज़ IMO कार्बन तीव्रता संकेतक (CII), FuelEU Maritime की पूल्ड GHG तीव्रता और EU ETS लागत।",
  "Deliverable 5 · Experimental results": "डिलिवरेबल 5 · प्रायोगिक परिणाम",
  "The quantum-inspired methods against conventional prediction and optimization methods on accuracy, convergence speed, solution quality and scalability, including cases where they do not win.":
    "क्वांटम-प्रेरित विधियों की पारंपरिक पूर्वानुमान और अनुकूलन विधियों से तुलना: सटीकता, अभिसरण गति, समाधान की गुणवत्ता और स्केलेबिलिटी पर, उन मामलों सहित जहाँ वे नहीं जीततीं।",
  "Prediction": "पूर्वानुमान",
  "Optimization": "अनुकूलन",
  "How it works": "यह कैसे काम करता है",
  "SIH 2026 problem statement 26138 (Egreen Quanta): quantum-inspired fuel consumption prediction and green fleet optimization.":
    "SIH 2026 समस्या कथन 26138 (Egreen Quanta): क्वांटम-प्रेरित ईंधन खपत पूर्वानुमान और हरित बेड़ा अनुकूलन।",

  // optimizer and plan
  "Algorithm": "एल्गोरिद्म",
  "Evaluation budget": "मूल्यांकन बजट",
  "Run optimization": "अनुकूलन चलाएँ",
  "Optimizing…": "अनुकूलन हो रहा है…",
  "waiting for {n} earlier run(s) on the shared server": "साझा सर्वर पर {n} पिछले रन की प्रतीक्षा",
  "searching the Pareto front": "पैरेटो फ्रंट खोजा जा रहा है",
  "looking for feasible plans": "व्यवहार्य योजनाएँ खोजी जा रही हैं",
  "{n} Pareto-optimal plans · {m} evaluated": "{n} पैरेटो-इष्टतम योजनाएँ · {m} योजनाओं का मूल्यांकन",
  "idle": "तैयार",
  "Jump to:": "सीधे देखें:",
  "Recommended (balanced)": "अनुशंसित (संतुलित)",
  "Minimum fuel": "न्यूनतम ईंधन",
  "Minimum emissions": "न्यूनतम उत्सर्जन",
  "Minimum cost": "न्यूनतम लागत",
  "Save plan": "योजना सहेजें",
  "Saved ✓": "सहेजी गई ✓",
  "Save as PDF": "PDF के रूप में सहेजें",
  "Download decision report": "निर्णय रिपोर्ट डाउनलोड करें",
  "Building report…": "रिपोर्ट बन रही है…",
  "{ships} ships on {services} services": "{services} सेवाओं पर {ships} जहाज़",
  "all constraints satisfied": "सभी शर्तें पूरी",
  "Fuel": "ईंधन",
  "Well-to-wake GHG": "वेल-टू-वेक GHG",
  "Annual cost": "वार्षिक लागत",
  "vs current practice": "मौजूदा तरीके की तुलना में",
  "Fleet allocation map": "बेड़ा आवंटन मानचित्र",
  "Emission profile by service": "सेवा-वार उत्सर्जन प्रोफ़ाइल",
  "Fleet allocation": "बेड़ा आवंटन",

  // scenario panel
  "Scenario": "परिदृश्य",
  "Year": "वर्ष",
  "EU ETS price (€/t)": "EU ETS मूल्य (€/t)",
  "Global carbon levy ($/t)": "वैश्विक कार्बन शुल्क ($/t)",
  "Fuel price ×": "ईंधन मूल्य ×",
  "pay penalty if non-compliant": "अनुपालन न होने पर दंड दें",
  "must comply": "अनुपालन अनिवार्य",
  "Min. on-time probability": "समय पर पहुँचने की न्यूनतम संभावना",
  "Min. CII rating": "न्यूनतम CII रेटिंग",
  "Red Sea closed (divert via Cape)": "लाल सागर बंद (केप के रास्ते)",
  "SW-monsoon sea state (+1 Bf)": "दक्षिण-पश्चिम मानसून समुद्री स्थिति (+1 Bf)",
  "Objectives:": "उद्देश्य:",
  "Schedule risk": "समय-सारिणी जोखिम",
  "WtW GHG": "वेल-टू-वेक GHG",
  "Cost": "लागत",
  "Upload your own routes (CSV)": "अपने मार्ग अपलोड करें (CSV)",
  "Hide": "छिपाएँ",
  "Fuel prices": "ईंधन मूल्य",
  "Hide fuel prices": "ईंधन मूल्य छिपाएँ",
  "Copy share link": "साझा लिंक कॉपी करें",
  "Link copied": "लिंक कॉपी हो गया",

  // compare
  "Saved plans": "सहेजी गई योजनाएँ",
  "Side by side": "साथ-साथ",
  "Fuel mix": "ईंधन मिश्रण",
  "Route by route": "मार्ग-दर-मार्ग",

  // headings used by the tour
  "Trade-off: emissions vs cost": "ट्रेड-ऑफ़: उत्सर्जन बनाम लागत",
  "Speed-fuel curve at these conditions": "इन परिस्थितियों में गति-ईंधन वक्र",
  "Transition pathway 2025 → 2050": "परिवर्तन मार्ग 2025 → 2050",
  "Gate-model QAOA": "गेट-मॉडल QAOA",
  "CII: attained ÷ required per service": "CII: प्रति सेवा प्राप्त ÷ आवश्यक",

  // guided tour
  "Guided tour · {i} / {n}": "गाइडेड टूर · {i} / {n}",
  "Close": "बंद करें",
  "Back": "पीछे",
  "Next": "आगे",
  "Finish": "समाप्त",
  "Running the optimizer… the Pareto front builds up on the page.": "अनुकूलक चल रहा है… पैरेटो फ्रंट पेज पर बनता जा रहा है।",
  "Start here: today's footprint": "यहाँ से शुरू करें: आज का उत्सर्जन",
  "The India coastal and near-sea network in 2030, 12 services. The big number is the fleet's well-to-wake emissions if it keeps running as it does today: VLSFO at the fastest schedule-feasible speed.":
    "2030 में भारत का तटीय और निकट-समुद्री नेटवर्क, 12 सेवाएँ। बड़ी संख्या बेड़े का वेल-टू-वेक उत्सर्जन है, अगर वह आज की तरह ही चलता रहे: VLSFO ईंधन, समय-सारिणी के भीतर सबसे तेज़ गति पर।",
  "The network on real sea lanes": "असली समुद्री मार्गों पर नेटवर्क",
  "Every service follows its real sea route. Once a plan is chosen, the map colours each route by the fuel it burns.":
    "हर सेवा अपने वास्तविक समुद्री मार्ग पर चलती है। योजना चुनने के बाद मानचित्र हर मार्ग को उसके ईंधन के रंग में दिखाता है।",
  "Optimise the whole fleet": "पूरे बेड़े का अनुकूलन",
  "Deliverables 2–3. QMOEA-H, our quantum-inspired optimizer, picks the vessel class, number of ships, speed, fuel and shore power for every service at once, minimising fuel, well-to-wake emissions and cost under demand, schedule, CII and FuelEU constraints. Press Next and the tour runs it for you.":
    "डिलिवरेबल 2–3। हमारा क्वांटम-प्रेरित अनुकूलक QMOEA-H हर सेवा के लिए जहाज़ की श्रेणी, जहाज़ों की संख्या, गति, ईंधन और तट-बिजली एक साथ चुनता है, और माँग, समय-सारिणी, CII और FuelEU की शर्तों के भीतर ईंधन, वेल-टू-वेक उत्सर्जन और लागत घटाता है। \"आगे\" दबाएँ, टूर इसे आपके लिए चला देगा।",
  "Trade-offs, not a single answer": "एक जवाब नहीं, कई संतुलन",
  "Each dot is a complete fleet plan that no other plan beats on every objective (a Pareto front). The ringed dot is the balanced recommendation; the grey markers are today's practice and slow steaming. Click any dot to inspect that plan.":
    "हर बिंदु एक पूरी बेड़ा योजना है जिसे कोई दूसरी योजना हर उद्देश्य पर नहीं हरा सकती (पैरेटो फ्रंट)। घेरे वाला बिंदु संतुलित अनुशंसा है; धूसर निशान आज का तरीका और धीमी गति (स्लो स्टीमिंग) हैं। किसी भी बिंदु पर क्लिक करके वह योजना देखें।",
  "The plan, service by service": "योजना, सेवा-दर-सेवा",
  "Vessel mix, ships, speed, fuel and shore power for each service, with a fleet map, an emission profile and a one-click decision report (Deliverable 4).":
    "हर सेवा के लिए जहाज़ों का मिश्रण, संख्या, गति, ईंधन और तट-बिजली, साथ में बेड़ा मानचित्र, उत्सर्जन प्रोफ़ाइल और एक क्लिक में निर्णय रिपोर्ट (डिलिवरेबल 4)।",
  "Deliverable 1. Q-PHYS predicts daily fuel from speed, load, weather and vessel type: a physics prior plus a tensor-network (MPS) model and monotone gradient boosting. The band is a 90 % conformal prediction interval. Move the sliders to see it respond.":
    "डिलिवरेबल 1। Q-PHYS गति, भार, मौसम और जहाज़ के प्रकार से रोज़ की ईंधन खपत का अनुमान लगाता है: भौतिकी आधारित अनुमान, टेंसर-नेटवर्क (MPS) मॉडल और मोनोटोन ग्रेडिएंट बूस्टिंग। पट्टी 90 % कन्फ़ॉर्मल पूर्वानुमान अंतराल है। स्लाइडर हिलाकर इसका असर देखें।",
  "2025 → 2050 scenarios": "2025 → 2050 परिदृश्य",
  "Scenario simulation: every milestone year is re-optimised as the CII and FuelEU limits tighten, prices change and green fuels reach more ports. Fuel prices, carbon price and disruptions such as a Red Sea diversion are set in the scenario panel.":
    "परिदृश्य सिमुलेशन: हर पड़ाव वर्ष का फिर से अनुकूलन होता है, क्योंकि CII और FuelEU की सीमाएँ सख़्त होती हैं, कीमतें बदलती हैं और हरित ईंधन ज़्यादा बंदरगाहों तक पहुँचते हैं। ईंधन मूल्य, कार्बन मूल्य और लाल सागर जैसी बाधाएँ परिदृश्य पैनल में तय होती हैं।",
  "A real quantum circuit": "एक असली क्वांटम सर्किट",
  "Four services competing for scarce ships, written as a 12-qubit QAOA circuit. It is simulated exactly and trained here, and it downloads as OpenQASM 2.0 that runs on IBM Quantum or any QASM toolchain.":
    "सीमित जहाज़ों के लिए होड़ करती चार सेवाएँ, 12-क्यूबिट QAOA सर्किट के रूप में। इसे यहीं सटीक रूप से सिमुलेट और प्रशिक्षित किया जाता है, और यह OpenQASM 2.0 फ़ाइल के रूप में डाउनलोड होता है जो IBM Quantum या किसी भी QASM टूलचेन पर चलती है।",
  "The chosen plan checked against IMO CII ratings per ship, the FuelEU Maritime GHG-intensity limit (with pooling) and EU ETS costs, year by year.":
    "चुनी गई योजना की साल-दर-साल जाँच: प्रति जहाज़ IMO CII रेटिंग, FuelEU Maritime की GHG-तीव्रता सीमा (पूलिंग सहित) और EU ETS लागत।",
  "Honest benchmarks": "ईमानदार बेंचमार्क",
  "Deliverable 5. QMOEA-H against NSGA-II, NSGA-III, SPEA2, MOEA/D, MOPSO and ablations over 10 seeds, with gaps to the exact MILP optimum and a scalability sweep up to 200 routes. Wins, ties and losses are all reported.":
    "डिलिवरेबल 5। QMOEA-H की NSGA-II, NSGA-III, SPEA2, MOEA/D, MOPSO और एब्लेशन से 10 सीड पर तुलना, सटीक MILP इष्टतम से अंतर और 200 मार्गों तक स्केलेबिलिटी जाँच के साथ। जीत, बराबरी और हार, सब दर्ज हैं।",
};

const DICTS: Record<Lang, Record<string, string>> = { en: {}, hi: HI };
const KEY = "qgf-lang";

interface Ctx { lang: Lang; setLang: (l: Lang) => void; t: (en: string, vars?: Record<string, string | number>) => string }
const LangCtx = createContext<Ctx | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    try { return localStorage.getItem(KEY) === "hi" ? "hi" : "en"; } catch { return "en"; }
  });
  useEffect(() => {
    document.documentElement.lang = lang;
    try { localStorage.setItem(KEY, lang); } catch { /* private mode */ }
  }, [lang]);
  const t = useCallback((en: string, vars?: Record<string, string | number>) => {
    let s = DICTS[lang][en] ?? en;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
    return s;
  }, [lang]);
  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);
  return <LangCtx.Provider value={value}>{children}</LangCtx.Provider>;
}

export function useLang(): Ctx {
  const v = useContext(LangCtx);
  if (!v) throw new Error("LangProvider missing");
  return v;
}

/** Shorthand for components that only translate. */
export const useT = () => useLang().t;
